[versions]
agp = "8.7.2"
kotlin = "1.9.24"
junitKtx = "1.2.1"

[libraries]
androidx_core_ktx = { module = "androidx.core:core-ktx", version = "1.9.0" }
androidx_appcompat = { module = "androidx.appcompat:appcompat", version = "1.6.1" }
material = { module = "com.google.android.material:material", version = "1.9.0" }
androidx_activity = { module = "androidx.activity:activity-ktx", version = "1.7.2" }
androidx_constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version = "2.1.4" }


# Test dependencies
junit = { module = "junit:junit", version = "4.13.2" }
androidx_junit = { module = "androidx.test.ext:junit", version = "1.1.5" }
androidx_espresso_core = { module = "androidx.test.espresso:espresso-core", version = "3.5.0" }
junit-ktx = { group = "androidx.test.ext", name = "junit-ktx", version.ref = "junitKtx" }


[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }

